[package]
name = "a16_hir"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "High-Level Intermediate Representation for A16"

[dependencies]
a16_ast = { path = "../a16_ast" }
smol_str.workspace = true
indexmap.workspace = true

[dev-dependencies]
a16_parser = { path = "../a16_parser" }
